services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth_app
      POSTGRES_PASSWORD: auth_app
      POSTGRES_DB: auth_app
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
